POST http://localhost:3008 HTTP/1.1
content-type: application/json

{
  "ref": "refs/heads/master",
  "compare_url": "https://dev-page.iambanban.com/api/compare/21edec...9d1919",
  "repository": {
    "id": 557,
    "owner": {
      "id": 20,
      "username": "ee-front",
      "login": "ee-front",
      "full_name": "ee-front",
      "email": "",
      "avatar_url": "http://114.55.7.123:3000/avatars/20"
    },
    "name": "page",
    "full_name": "ee-front/page",
    "description": "page活动页源码",
    "private": true,
    "fork": false,
    "parent": null,
    "empty": false,
    "mirror": false,
    "size": 431008768,
    "html_url": "http://114.55.7.123:3000/ee-front/page",
    "ssh_url": "git@114.55.7.123:ee-front/page.git",
    "clone_url": "http://114.55.7.123:3000/ee-front/page.git",
    "website": "",
    "stars_count": 0,
    "forks_count": 0,
    "watchers_count": 14,
    "open_issues_count": 0,
    "default_branch": "master",
    "created_at": "2022-01-12T11:45:20+08:00",
    "updated_at": "2022-04-30T13:34:59+08:00"
  },
  "sender": {
    "id": 221,
    "username": "tao.lijuan",
    "login": "tao.lijuan",
    "full_name": "",
    "email": "tao.lijuan@olaola.chat",
    "avatar_url": "http://114.55.7.123:3000/avatars/221"
  }
}